### ISSUE TITLE
Logotype

### ISSUE THREAD

**Issue by nunojesus** [alexprengere/currencyconverter#10]
Hello, I read your work, and this is an amazing project, congrats for that! Im a graphic designer that contributes for opensource projects like yours, so if you need some help to create a logotype or other stuff just say it.

Greetings!

**Comment by alexprengere** [comment]
Thanks a lot, this has to be one of the nicest thing said to me on a GitHub issue 😉 . I don't think the currency converter is in urgent need of a shiny new logo, and I would not want to waste your time asking for one. But if you ever want to submit something, I would gladly include it.

**Comment by nunojesus** [comment]
Hello, I dont think it will be a waste of my time, I enjoy to create designs. 
Do you have any request for the logo? Color? 

Greetings!
Nuno Jesus

**Comment by alexprengere** [comment]
Honestly, apart from the fact that it should remind people of "currency", I have no idea 😄.

**Comment by nunojesus** [comment]
Hello, here is the design that I create for your Currency Converter, I think it´s very modern and different from the other conversors. I hope you like it, if you want to change something just say it.

Greetings

![conversor monetario3](https://user-images.githubusercontent.com/34600369/41346895-eb5dc8e0-6eff-11e8-96f2-052eef346ed6.png)

**Comment by alexprengere** [comment]
Wow, that is really beautiful. I integrated the logo with 8a5cf89, it should now be visible on the [front page](https://github.com/alexprengere/currencyconverter).

Thanks!

**Comment by alexprengere** [comment]
Closed with PR #11
