### ISSUE TITLE
Detach tool local file; include API requests

### ISSUE THREAD

**Issue by DarioHett** [alexprengere/currencyconverter#14]
Hi Alex,

what do you think of detaching the tool from the basic .zip-file of the ECB homepage and instead make on-the-fly requests through the ECB API?

The http request looks like the following. A key would be D.USD.EUR.SP00.A for USD/EUR daily under the 'flowRef' EXR for Exchange Rates. 
```
class EcbCurrencyConverter(CurrencyConverter):
    def ecb_request(key,flowRef, *pargs, **kargs):
        #get data
        url = 'https://sdw-wsrest.ecb.europa.eu/service/data/'+flowRef+'/'+key
        if kargs:
            url = url+'?'+param_url(kargs)
        print('Requested URL: '+url)
        r = requests.get(url,
                headers={'Accept':'text/csv'})
        return r
```

The API allows for further customisation using parameters in the URL([ECB SDMX 2.1 RESTful web service](https://sdw-wsrest.ecb.europa.eu/web/generator/index.html#tabData))
```
    def param_url(dict):
        param = ''
        for k,v in dict.items():
            param = param+k+'='+v+'&'
        param = param[:-1] #removes the last '&' sign
        return param
```

Returning a [[date,rate],[date, rate],...] per request or currency would look like:
```
    def ecb_read(ecb_request):
        r = ecb_request.content.decode().splitlines()
        c = csv.reader(r)
        date_rate = []
        for row in c:
            date_rate.append(row[6:8])
        return date_rate
```

And attaches here to your original (super)class
```
    def load_file(self, currency_file, **kargs):
        """currency_file here just takes the requested currency
        for example: 'USD'"""
        content = self.ecb_request(currency_file, 'EXR')
        self.load_lines(content)
```

I will have to do some work to properly set up the subclass (which might take some time due to lack of experience and work) but you get the idea.

This would also lend itself easily going forward to extend the tool to further sources and such have a more complete set of currencies.

Best regards
Dario

**Comment by alexprengere** [comment]
Well, congratulations for you first contribution 😉 You are doing great!

If you do not need the full dataset, I suggest to just use `head` on the file to keep only the first lines, it should work well and reduce the disk usage. Note that the full dataset is only 1Mo uncompressed though. But I understand if you need to cut down on the initial load time of 400ms.

I am not sure I understand your last point but I will try to answer it. You can pass `currency_file=None` during `__init__` to avoid calling `load_file`. Then you can call `load_lines`  with your custom data (it expects the first line to be the header).

```python
c = CurrencyConverter(currency_file=None)
c.load_lines(open('eurofxref-hist.csv'))
```

**Comment by alexprengere** [comment]
I have never had those use cases so I did not really think about it.

I guess the easiest way to extend an object with new data is actually to create it from scratch again with the previous lines concatenated with new additional lines (custom code to handle this use case would have to be justified, since we are only talking about a few ms of processing time).

```python
lines = list(open('eurofxref-hist.csv'))

c1 = CurrencyConverter(currency_file=None)
c1.load_lines(lines)

# Get other_lines from somewhere else
c2 = CurrencyConverter(currency_file=None)
c2.load_lines(lines + other_lines)
``` 

For your second point, I did not concatenate the lists because they were not concatenated in the raw data set. I guess you could merge them manually if needed, either in the CSV, or using the `_rates`, but I think the current system works well, e.g. to have them as two separate currencies.
