### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by tomfrankel** [alexprengere/currencyconverter#21]
Hi,

In Python 3.7,  c=CurrencyConverter() works, but

c = CurrencyConverter('http://www.ecb.europa.eu/stats/eurofxref/eurofxref.zip')
c = CurrencyConverter('https://www.ecb.europa.eu/stats/eurofxref/eurofxref.zip')
c = CurrencyConverter('http://www.ecb.int/stats/eurofxref/eurofxref-hist.zip')
c = CurrencyConverter('https://www.ecb.int/stats/eurofxref/eurofxref-hist.zip')

all trigger an SSLCertVerificationError : certificate verify failed: unable to get local issuer certificate (_ssl.cL1045).

I tried it in 2.7 and there are no issues - it loads the current tables from the ecb without a problem.

**Comment by tomfrankel** [comment]
Ok, adding this (from here:  https://medium.com/@moreless/how-to-fix-python-ssl-certificate-verify-failed-97772d9dd14c)  worked:

import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
getattr(ssl, '_create_unverified_context', None)):
     ssl._create_default_https_context = ssl._create_unverified_context

Thanks for maintaining Currency Converter.

**Comment by alexprengere** [comment]
Thanks you for the solution!
