### ISSUE TITLE
Rates Not Updating

### ISSUE THREAD

**Issue by tyronecragg** [alexprengere/currencyconverter#23]
Hi there,

It appears to me that the rates in the package haven't updated for over a month. When I run a conversion request for today's date, for example:

_c.convert(1, 'EUR', 'USD', date=date(2020, 11, 16))_

the package returns the error:

_RateNotFoundError: 2020-11-16 not in USD bounds 1999-01-04/2020-09-24_

I would have expected the rates to update more frequently, but is this the intended behaviour of the package?

Thanks!

**Comment by tyronecragg** [comment]
Apologies, I found a closed issue that addresses this.

**Comment by alexprengere** [comment]
Hi!
No problem, the fact that this has come up more than once is probably a sign that the documentation could be improved.
More details in #18, but for those who are reading this, the data embedded in the library is not updated often (on PyPI).
If you need the latest rates, you can just do:

```python
from currency_converter import CurrencyConverter
c = CurrencyConverter('http://www.ecb.int/stats/eurofxref/eurofxref-hist.zip')
```
