### ISSUE TITLE
Documentation needed?

### ISSUE THREAD

**Issue by Leo-Ryu** [alexprengere/currencyconverter#24]
Hello,

I’ve been working on a platform for editable codebase documentation and noticed this repo lacked documentation besides the README. Would it be useful if I generated/hosted docs for this repo?

The platform:

1) has a modern markdown editor to allow people to quickly and easily create new documents/user guides
2) is similar to readthedocs/sphinx in that reads through the codebase and builds/hosts linkable pages describing classes and functions, as well as their usages in the codebase. However unlike readthedocs/sphinx, it doesn't require any configuration to get up and running
3) tracks the github repo so that every build has the latest code

Sincerely hoping I can be of use to you and your project!

**Comment by alexprengere** [comment]
Thanks! This sounds like a good idea. I think the README contains everything you need to know to use the library, but having an extensive documentation of the internals would be great.
For other projects of mine I use readthedocs, but if you want to submit a PR or set up something else, this would be great too.

**Comment by Leo-Ryu** [comment]
Awesome! I'll open up a PR
