### ISSUE TITLE
Other Currncies Data Source.

### ISSUE THREAD

**Issue by bmarchenko** [alexprengere/currencyconverter#3]
Hello, 
ECB has rates for only 42 main currencies. Does anybody know the reliable source of similar information for other currencies?

**Comment by alexprengere** [comment]
As far as I know, you can use [xe.com](http://www.xe.com/xecurrencydata/pricing.php) to get more currencies, but it is pretty expensive. 

Note that if you can get your hands on any currency dataset, as long as it is formatted the same way as ECB data, you can use it with:

```python
>>> c = CurrencyConverter('./path/to/currency/file.csv')
```

**Comment by mflatischler** [comment]
Hi!

After some googling, i stumbled upon Yahoo Finance' [YQL](https://developer.yahoo.com/yql/) : [example](https://developer.yahoo.com/yql/console/?q=&env=store://datatables.org/alltableswithkeys#h=select+*+from+yahoo.finance.historicaldata+where+symbol+%3D+%22BND%3DX%22+and+startDate+%3D+%222009-09-11%22+and+endDate+%3D+%222010-03-10%22)

further reading: [Get Realtime Stock Quotes using Yahoo Finance API](http://meumobi.github.io/stocks%20apis/2016/03/13/get-realtime-stock-quotes-yahoo-finance-api.html)
