### ISSUE TITLE
fallback option not working 

### ISSUE THREAD

**Issue by aman9d** [alexprengere/currencyconverter#30]
HI, Thanks for this amazing project, But while using this I found that data is not available for weekends and holidays and with parameter "fallback_on_missing_rate" there is no difference getting same error

 c = CurrencyConverter(fallback_on_missing_rate=True)
c.convert(100, 'RUB', date=(2017, 12, 2))

Error
RateNotFoundError: (2017, 12, 2) not in RUB bounds 2005-04-01/2021-05-17

**Comment by alexprengere** [comment]
You are providing the *date=* as a tuple, but what you need here is a `datetime.date` object:

```python
>>> from datetime import date
>>> c = CurrencyConverter(fallback_on_missing_rate=True)
>>> c.convert(100, 'RUB', date=date(2017, 12, 2))
1.4342339206839956
```
I agree the error is not really helpful here, because a simple dict lookup is done, and when it fails, you just get a generic error message that the rate was not found.
