### ISSUE TITLE
Human readable flag

### ISSUE THREAD

**Issue by vedangj044** [alexprengere/currencyconverter#31]
Much like we have `ls -lh` to print the sizes of file in human-readable format, we can have a `-h` or `--human` flag or/and a `-w`  flag for the currency.

Output may look like
`currency_converter 100 USD --to INR -h`
`100 USD  = 7,300 INR on Date`

also, 
`currency_converter 100 USD --to INR -w`
`100 USD = 7300 ( Seven thousand three hundred ) on Date`

Great tool BTW

**Comment by alexprengere** [comment]
Today we already have:

```bash
$ currency_converter 100 USD --to INR
100.000 USD = 7300.067 INR on 2021-03-09
```
So I am not sure what extra information we could add with a new flag `-h`, unless you suggested to keep the output as it is today for `-h`, and have something simpler when that option is omitted.
For `-w` I am not convinced about the usefulness of the feature, there are [libraries](https://pypi.org/project/num2words/) that do this if necessary, but I would prefer to not bring a dependency, where today there is none, and that is a feature 😉 .

**Comment by vedangj044** [comment]
Okay, I agree with you on the `-w` part about not introducing any dependency.

For the `-h` the output should be printed with commas, which IMO is more human readable.

`100 USD = 7,302 INR`

**Comment by alexprengere** [comment]
I pushed 4199c54ac235aeb5116be1c5ee5a6e0cc7a46c9d that should add those commas all the time, I do not think we need to add the extra `-h` option.

**Comment by vedangj044** [comment]
Yep! that's awesome. Thanks!
