### ISSUE TITLE
QAR conversion is not supported.

### ISSUE THREAD

**Issue by pcbzmani** [alexprengere/currencyconverter#43]
This website https://www.ecb.europa.eu/ not have conversion rate for QAR.

raise ValueError(f"{c} is not a supported currency")
ValueError: QAR is not a supported currency

**Comment by alexprengere** [comment]
Same answer as #35. If you find a currency data source that supports QAR, then you can format that data in a compatible way (basically, a CSV file), then pass it to the CurrencyConverter constructor (see README).
