### ISSUE TITLE
Incorrect coversion rate found

### ISSUE THREAD

**Issue by Bugvi-Benjamin-M** [alexprengere/currencyconverter#48]
Converting from DKK to USD with date 2023-08-09 gives an incorrect result.

As can be seen here:
<img width="724" alt="Screenshot 2023-09-22 at 17 31 54" src="https://github.com/alexprengere/currencyconverter/assets/38207818/c2dd6191-42d3-4c55-8f22-3c2e350b34cf">

This is clearly not the correct conversion rate. The day before, i.e., 2023-08-08:
<img width="708" alt="billede" src="https://github.com/alexprengere/currencyconverter/assets/38207818/22861924-6c19-4ec7-ac59-f933cb6a4202">

I also checked with ECB and if I use their website to convert with the given date it also seems fine.

**Comment by alexprengere** [comment]
I think you have the wrong GitHub project. Here is how you would do this "here":

```python
>>> from datetime import date
>>> from currency_converter import CurrencyConverter
>>> c = CurrencyConverter()

>>> c.convert(1, "DKK", "USD", date=date(2023, 8, 9))
0.1471997423199259
>>> c.convert(1, "DKK", "USD", date=date(2023, 8, 8))
0.14686975776689257
```

We also rely on ECB data, and it looks correct. 
You should either report this issue in [their repo](https://github.com/MicroPyramid/forex-python) or use [CurrencyConverter](https://pypi.org/project/CurrencyConverter/) 😉

**Comment by Bugvi-Benjamin-M** [comment]
Oh boy. My apologies! How embarrassing.

But now at least I get to use a proper currency converter that actually works! Thanks heaps!
